// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/tikasan/eventory-goa/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty
//
// API "eventory": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"../app"
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
	"time"
)

// イベント
type events struct {
	ID         int    `gorm:"primary_key"` // primary key
	APIType    string `gorm:"column:a_p_i_type"`
	Accepte    int
	Address    string
	Identifier string
	Limits     int
	URL        string `gorm:"column:u_r_l"`
	Wait       int
	CreatedAt  time.Time  // timestamp
	DeletedAt  *time.Time // nullable timestamp (soft delete)
	EndAt      time.Time  // timestamp
	StartAt    time.Time  // timestamp
	UpdatedAt  time.Time  // timestamp
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m events) TableName() string {
	return "events"

}

// eventsDB is the implementation of the storage interface for
// events.
type eventsDB struct {
	Db *gorm.DB
}

// NeweventsDB creates a new storage type.
func NeweventsDB(db *gorm.DB) *eventsDB {
	return &eventsDB{Db: db}
}

// DB returns the underlying database.
func (m *eventsDB) DB() interface{} {
	return m.Db
}

// eventsStorage represents the storage interface.
type eventsStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*events, error)
	Get(ctx context.Context, id int) (*events, error)
	Add(ctx context.Context, events *events) error
	Update(ctx context.Context, events *events) error
	Delete(ctx context.Context, id int) error

	ListEvent(ctx context.Context) []*app.Event
	OneEvent(ctx context.Context, id int) (*app.Event, error)
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *eventsDB) TableName() string {
	return "events"

}

// CRUD Functions

// Get returns a single events as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *eventsDB) Get(ctx context.Context, id int) (*events, error) {
	defer goa.MeasureSince([]string{"goa", "db", "events", "get"}, time.Now())

	var native events
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of events
func (m *eventsDB) List(ctx context.Context) ([]*events, error) {
	defer goa.MeasureSince([]string{"goa", "db", "events", "list"}, time.Now())

	var objs []*events
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *eventsDB) Add(ctx context.Context, model *events) error {
	defer goa.MeasureSince([]string{"goa", "db", "events", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding events", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *eventsDB) Update(ctx context.Context, model *events) error {
	defer goa.MeasureSince([]string{"goa", "db", "events", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating events", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *eventsDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "events", "delete"}, time.Now())

	var obj events

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting events", "error", err.Error())
		return err
	}

	return nil
}
