// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/tikasan/eventory-goa/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty
//
// API "eventory": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"../app"
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
	"time"
)

// ジャンル
type Genres struct {
	ID               int           `gorm:"primary_key"` // primary key
	EventGenres      []EventGenres // has many EventGenres
	Keyword          string
	Name             string
	UserFollowGenres []UserFollowGenres // has many UserFollowGenres
	CreatedAt        time.Time          // timestamp
	DeletedAt        *time.Time         // nullable timestamp (soft delete)
	UpdatedAt        time.Time          // timestamp
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m Genres) TableName() string {
	return "genres"

}

// GenresDB is the implementation of the storage interface for
// Genres.
type GenresDB struct {
	Db *gorm.DB
}

// NewGenresDB creates a new storage type.
func NewGenresDB(db *gorm.DB) *GenresDB {
	return &GenresDB{Db: db}
}

// DB returns the underlying database.
func (m *GenresDB) DB() interface{} {
	return m.Db
}

// GenresStorage represents the storage interface.
type GenresStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*Genres, error)
	Get(ctx context.Context, id int) (*Genres, error)
	Add(ctx context.Context, genres *Genres) error
	Update(ctx context.Context, genres *Genres) error
	Delete(ctx context.Context, id int) error

	ListGenre(ctx context.Context) []*app.Genre
	OneGenre(ctx context.Context, id int) (*app.Genre, error)
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *GenresDB) TableName() string {
	return "genres"

}

// CRUD Functions

// Get returns a single Genres as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *GenresDB) Get(ctx context.Context, id int) (*Genres, error) {
	defer goa.MeasureSince([]string{"goa", "db", "genres", "get"}, time.Now())

	var native Genres
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of Genres
func (m *GenresDB) List(ctx context.Context) ([]*Genres, error) {
	defer goa.MeasureSince([]string{"goa", "db", "genres", "list"}, time.Now())

	var objs []*Genres
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *GenresDB) Add(ctx context.Context, model *Genres) error {
	defer goa.MeasureSince([]string{"goa", "db", "genres", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding Genres", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *GenresDB) Update(ctx context.Context, model *Genres) error {
	defer goa.MeasureSince([]string{"goa", "db", "genres", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating Genres", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *GenresDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "genres", "delete"}, time.Now())

	var obj Genres

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting Genres", "error", err.Error())
		return err
	}

	return nil
}
