// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/tikasan/eventory-goa/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty
//
// API "eventory": Model Helpers
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"../app"
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
	"time"
)

// MediaType Retrieval Functions

// ListGenre returns an array of view: default.
func (m *GenresDB) ListGenre(ctx context.Context) []*app.Genre {
	defer goa.MeasureSince([]string{"goa", "db", "genre", "listgenre"}, time.Now())

	var native []*Genres
	var objs []*app.Genre
	err := m.Db.Scopes().Table(m.TableName()).Find(&native).Error

	if err != nil {
		goa.LogError(ctx, "error listing Genres", "error", err.Error())
		return objs
	}

	for _, t := range native {
		objs = append(objs, t.GenresToGenre())
	}

	return objs
}

// GenresToGenre loads a Genres and builds the default view of media type Genre.
func (m *Genres) GenresToGenre() *app.Genre {
	genres := &app.Genre{}
	genres.Name = &m.Name

	return genres
}

// OneGenre loads a Genres and builds the default view of media type Genre.
func (m *GenresDB) OneGenre(ctx context.Context, id int) (*app.Genre, error) {
	defer goa.MeasureSince([]string{"goa", "db", "genre", "onegenre"}, time.Now())

	var native Genres
	err := m.Db.Scopes().Table(m.TableName()).Preload("EventGenres").Preload("UserFollowGenres").Where("id = ?", id).Find(&native).Error

	if err != nil && err != gorm.ErrRecordNotFound {
		goa.LogError(ctx, "error getting Genres", "error", err.Error())
		return nil, err
	}

	view := *native.GenresToGenre()
	return &view, err
}
