// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/tikasan/eventory-goa/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty
//
// API "eventory": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
	"time"
)

// 都道府県
type prefs struct {
	ID        int `gorm:"primary_key"` // primary key
	Name      string
	CreatedAt time.Time  // timestamp
	DeletedAt *time.Time // nullable timestamp (soft delete)
	UpdatedAt time.Time  // timestamp
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m prefs) TableName() string {
	return "prefs"

}

// prefsDB is the implementation of the storage interface for
// prefs.
type prefsDB struct {
	Db *gorm.DB
}

// NewprefsDB creates a new storage type.
func NewprefsDB(db *gorm.DB) *prefsDB {
	return &prefsDB{Db: db}
}

// DB returns the underlying database.
func (m *prefsDB) DB() interface{} {
	return m.Db
}

// prefsStorage represents the storage interface.
type prefsStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*prefs, error)
	Get(ctx context.Context, id int) (*prefs, error)
	Add(ctx context.Context, prefs *prefs) error
	Update(ctx context.Context, prefs *prefs) error
	Delete(ctx context.Context, id int) error
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *prefsDB) TableName() string {
	return "prefs"

}

// CRUD Functions

// Get returns a single prefs as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *prefsDB) Get(ctx context.Context, id int) (*prefs, error) {
	defer goa.MeasureSince([]string{"goa", "db", "prefs", "get"}, time.Now())

	var native prefs
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of prefs
func (m *prefsDB) List(ctx context.Context) ([]*prefs, error) {
	defer goa.MeasureSince([]string{"goa", "db", "prefs", "list"}, time.Now())

	var objs []*prefs
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *prefsDB) Add(ctx context.Context, model *prefs) error {
	defer goa.MeasureSince([]string{"goa", "db", "prefs", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding prefs", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *prefsDB) Update(ctx context.Context, model *prefs) error {
	defer goa.MeasureSince([]string{"goa", "db", "prefs", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating prefs", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *prefsDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "prefs", "delete"}, time.Now())

	var obj prefs

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting prefs", "error", err.Error())
		return err
	}

	return nil
}
