// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/tikasan/eventory-goa/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty
//
// API "eventory": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
	"time"
)

// 都道府県
type Prefs struct {
	ID              int      `gorm:"primary_key"` // primary key
	Events          []Events // has many Events
	Name            string
	UserFollowPrefs []UserFollowPrefs // has many UserFollowPrefs
	CreatedAt       time.Time         // timestamp
	DeletedAt       *time.Time        // nullable timestamp (soft delete)
	UpdatedAt       time.Time         // timestamp
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m Prefs) TableName() string {
	return "prefs"

}

// PrefsDB is the implementation of the storage interface for
// Prefs.
type PrefsDB struct {
	Db *gorm.DB
}

// NewPrefsDB creates a new storage type.
func NewPrefsDB(db *gorm.DB) *PrefsDB {
	return &PrefsDB{Db: db}
}

// DB returns the underlying database.
func (m *PrefsDB) DB() interface{} {
	return m.Db
}

// PrefsStorage represents the storage interface.
type PrefsStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*Prefs, error)
	Get(ctx context.Context, id int) (*Prefs, error)
	Add(ctx context.Context, prefs *Prefs) error
	Update(ctx context.Context, prefs *Prefs) error
	Delete(ctx context.Context, id int) error
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *PrefsDB) TableName() string {
	return "prefs"

}

// CRUD Functions

// Get returns a single Prefs as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *PrefsDB) Get(ctx context.Context, id int) (*Prefs, error) {
	defer goa.MeasureSince([]string{"goa", "db", "prefs", "get"}, time.Now())

	var native Prefs
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of Prefs
func (m *PrefsDB) List(ctx context.Context) ([]*Prefs, error) {
	defer goa.MeasureSince([]string{"goa", "db", "prefs", "list"}, time.Now())

	var objs []*Prefs
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *PrefsDB) Add(ctx context.Context, model *Prefs) error {
	defer goa.MeasureSince([]string{"goa", "db", "prefs", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding Prefs", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *PrefsDB) Update(ctx context.Context, model *Prefs) error {
	defer goa.MeasureSince([]string{"goa", "db", "prefs", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating Prefs", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *PrefsDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "prefs", "delete"}, time.Now())

	var obj Prefs

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting Prefs", "error", err.Error())
		return err
	}

	return nil
}
