// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/tikasan/eventory-goa/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty
//
// API "eventory": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
	"time"
)

// ユーザーのフォロージャンル
type user_follow_genres struct {
	ID        int `gorm:"primary_key"` // primary key
	GenreID   int
	UserID    int
	CreatedAt time.Time  // timestamp
	DeletedAt *time.Time // nullable timestamp (soft delete)
	UpdatedAt time.Time  // timestamp
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m user_follow_genres) TableName() string {
	return "user_follow_genres"

}

// user_follow_genresDB is the implementation of the storage interface for
// user_follow_genres.
type user_follow_genresDB struct {
	Db *gorm.DB
}

// Newuser_follow_genresDB creates a new storage type.
func Newuser_follow_genresDB(db *gorm.DB) *user_follow_genresDB {
	return &user_follow_genresDB{Db: db}
}

// DB returns the underlying database.
func (m *user_follow_genresDB) DB() interface{} {
	return m.Db
}

// user_follow_genresStorage represents the storage interface.
type user_follow_genresStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*user_follow_genres, error)
	Get(ctx context.Context, id int) (*user_follow_genres, error)
	Add(ctx context.Context, userFollowGenres *user_follow_genres) error
	Update(ctx context.Context, userFollowGenres *user_follow_genres) error
	Delete(ctx context.Context, id int) error
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *user_follow_genresDB) TableName() string {
	return "user_follow_genres"

}

// CRUD Functions

// Get returns a single user_follow_genres as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *user_follow_genresDB) Get(ctx context.Context, id int) (*user_follow_genres, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userFollowGenres", "get"}, time.Now())

	var native user_follow_genres
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of user_follow_genres
func (m *user_follow_genresDB) List(ctx context.Context) ([]*user_follow_genres, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userFollowGenres", "list"}, time.Now())

	var objs []*user_follow_genres
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *user_follow_genresDB) Add(ctx context.Context, model *user_follow_genres) error {
	defer goa.MeasureSince([]string{"goa", "db", "userFollowGenres", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding user_follow_genres", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *user_follow_genresDB) Update(ctx context.Context, model *user_follow_genres) error {
	defer goa.MeasureSince([]string{"goa", "db", "userFollowGenres", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating user_follow_genres", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *user_follow_genresDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "userFollowGenres", "delete"}, time.Now())

	var obj user_follow_genres

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting user_follow_genres", "error", err.Error())
		return err
	}

	return nil
}
