// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/tikasan/eventory-goa/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty
//
// API "eventory": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
	"time"
)

// ユーザーのキープ状態
type user_keep_status struct {
	ID             int `gorm:"primary_key"` // primary key
	BatchProcessed bool
	EventID        int
	Status         string
	UserID         int
	CreatedAt      time.Time  // timestamp
	DeletedAt      *time.Time // nullable timestamp (soft delete)
	UpdatedAt      time.Time  // timestamp
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m user_keep_status) TableName() string {
	return "user_keep_statuses"

}

// user_keep_statusDB is the implementation of the storage interface for
// user_keep_status.
type user_keep_statusDB struct {
	Db *gorm.DB
}

// Newuser_keep_statusDB creates a new storage type.
func Newuser_keep_statusDB(db *gorm.DB) *user_keep_statusDB {
	return &user_keep_statusDB{Db: db}
}

// DB returns the underlying database.
func (m *user_keep_statusDB) DB() interface{} {
	return m.Db
}

// user_keep_statusStorage represents the storage interface.
type user_keep_statusStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*user_keep_status, error)
	Get(ctx context.Context, id int) (*user_keep_status, error)
	Add(ctx context.Context, userKeepStatus *user_keep_status) error
	Update(ctx context.Context, userKeepStatus *user_keep_status) error
	Delete(ctx context.Context, id int) error
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *user_keep_statusDB) TableName() string {
	return "user_keep_statuses"

}

// CRUD Functions

// Get returns a single user_keep_status as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *user_keep_statusDB) Get(ctx context.Context, id int) (*user_keep_status, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userKeepStatus", "get"}, time.Now())

	var native user_keep_status
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of user_keep_status
func (m *user_keep_statusDB) List(ctx context.Context) ([]*user_keep_status, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userKeepStatus", "list"}, time.Now())

	var objs []*user_keep_status
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *user_keep_statusDB) Add(ctx context.Context, model *user_keep_status) error {
	defer goa.MeasureSince([]string{"goa", "db", "userKeepStatus", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding user_keep_status", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *user_keep_statusDB) Update(ctx context.Context, model *user_keep_status) error {
	defer goa.MeasureSince([]string{"goa", "db", "userKeepStatus", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating user_keep_status", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *user_keep_statusDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "userKeepStatus", "delete"}, time.Now())

	var obj user_keep_status

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting user_keep_status", "error", err.Error())
		return err
	}

	return nil
}
