// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/tikasan/eventory-goa/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty
//
// API "eventory": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
	"time"
)

// ユーザーの端末情報
type UserTerminals struct {
	ID            int `gorm:"primary_key"` // primary key
	ClientVersion string
	Identifier    bool
	Platform      string
	Token         string
	UserID        int        // has many UserTerminals
	CreatedAt     time.Time  // timestamp
	DeletedAt     *time.Time // nullable timestamp (soft delete)
	UpdatedAt     time.Time  // timestamp
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m UserTerminals) TableName() string {
	return "user_terminals"

}

// UserTerminalsDB is the implementation of the storage interface for
// UserTerminals.
type UserTerminalsDB struct {
	Db *gorm.DB
}

// NewUserTerminalsDB creates a new storage type.
func NewUserTerminalsDB(db *gorm.DB) *UserTerminalsDB {
	return &UserTerminalsDB{Db: db}
}

// DB returns the underlying database.
func (m *UserTerminalsDB) DB() interface{} {
	return m.Db
}

// UserTerminalsStorage represents the storage interface.
type UserTerminalsStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*UserTerminals, error)
	Get(ctx context.Context, id int) (*UserTerminals, error)
	Add(ctx context.Context, userterminals *UserTerminals) error
	Update(ctx context.Context, userterminals *UserTerminals) error
	Delete(ctx context.Context, id int) error
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *UserTerminalsDB) TableName() string {
	return "user_terminals"

}

// CRUD Functions

// Get returns a single UserTerminals as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *UserTerminalsDB) Get(ctx context.Context, id int) (*UserTerminals, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminals", "get"}, time.Now())

	var native UserTerminals
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of UserTerminals
func (m *UserTerminalsDB) List(ctx context.Context) ([]*UserTerminals, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminals", "list"}, time.Now())

	var objs []*UserTerminals
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *UserTerminalsDB) Add(ctx context.Context, model *UserTerminals) error {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminals", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding UserTerminals", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *UserTerminalsDB) Update(ctx context.Context, model *UserTerminals) error {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminals", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating UserTerminals", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *UserTerminalsDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminals", "delete"}, time.Now())

	var obj UserTerminals

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting UserTerminals", "error", err.Error())
		return err
	}

	return nil
}
