// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/tikasan/eventory-goa/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty
//
// API "eventory": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
	"time"
)

// ユーザー
type users struct {
	ID        int `gorm:"primary_key"` // primary key
	Email     string
	Name      string
	CreatedAt time.Time  // timestamp
	DeletedAt *time.Time // nullable timestamp (soft delete)
	UpdatedAt time.Time  // timestamp
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m users) TableName() string {
	return "users"

}

// usersDB is the implementation of the storage interface for
// users.
type usersDB struct {
	Db *gorm.DB
}

// NewusersDB creates a new storage type.
func NewusersDB(db *gorm.DB) *usersDB {
	return &usersDB{Db: db}
}

// DB returns the underlying database.
func (m *usersDB) DB() interface{} {
	return m.Db
}

// usersStorage represents the storage interface.
type usersStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*users, error)
	Get(ctx context.Context, id int) (*users, error)
	Add(ctx context.Context, users *users) error
	Update(ctx context.Context, users *users) error
	Delete(ctx context.Context, id int) error
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *usersDB) TableName() string {
	return "users"

}

// CRUD Functions

// Get returns a single users as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *usersDB) Get(ctx context.Context, id int) (*users, error) {
	defer goa.MeasureSince([]string{"goa", "db", "users", "get"}, time.Now())

	var native users
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of users
func (m *usersDB) List(ctx context.Context) ([]*users, error) {
	defer goa.MeasureSince([]string{"goa", "db", "users", "list"}, time.Now())

	var objs []*users
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *usersDB) Add(ctx context.Context, model *users) error {
	defer goa.MeasureSince([]string{"goa", "db", "users", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding users", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *usersDB) Update(ctx context.Context, model *users) error {
	defer goa.MeasureSince([]string{"goa", "db", "users", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating users", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *usersDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "users", "delete"}, time.Now())

	var obj users

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting users", "error", err.Error())
		return err
	}

	return nil
}
