// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/tikasan/eventory-goa/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty
//
// API "eventory": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
	"time"
)

// ユーザーの端末情報
type user_terminals struct {
	ID            int `gorm:"primary_key"` // primary key
	ClientVersion string
	Identifier    bool
	Platform      string
	Token         string
	UserID        int
	CreatedAt     time.Time  // timestamp
	DeletedAt     *time.Time // nullable timestamp (soft delete)
	UpdatedAt     time.Time  // timestamp
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m user_terminals) TableName() string {
	return "user_terminals"

}

// user_terminalsDB is the implementation of the storage interface for
// user_terminals.
type user_terminalsDB struct {
	Db *gorm.DB
}

// Newuser_terminalsDB creates a new storage type.
func Newuser_terminalsDB(db *gorm.DB) *user_terminalsDB {
	return &user_terminalsDB{Db: db}
}

// DB returns the underlying database.
func (m *user_terminalsDB) DB() interface{} {
	return m.Db
}

// user_terminalsStorage represents the storage interface.
type user_terminalsStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*user_terminals, error)
	Get(ctx context.Context, id int) (*user_terminals, error)
	Add(ctx context.Context, userTerminals *user_terminals) error
	Update(ctx context.Context, userTerminals *user_terminals) error
	Delete(ctx context.Context, id int) error
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *user_terminalsDB) TableName() string {
	return "user_terminals"

}

// CRUD Functions

// Get returns a single user_terminals as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *user_terminalsDB) Get(ctx context.Context, id int) (*user_terminals, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminals", "get"}, time.Now())

	var native user_terminals
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of user_terminals
func (m *user_terminalsDB) List(ctx context.Context) ([]*user_terminals, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminals", "list"}, time.Now())

	var objs []*user_terminals
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *user_terminalsDB) Add(ctx context.Context, model *user_terminals) error {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminals", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding user_terminals", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *user_terminalsDB) Update(ctx context.Context, model *user_terminals) error {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminals", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating user_terminals", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *user_terminalsDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminals", "delete"}, time.Now())

	var obj user_terminals

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting user_terminals", "error", err.Error())
		return err
	}

	return nil
}
