// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/tikasan/eventory-goa/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty
//
// API "eventory": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
	"time"
)

// ユーザー
type Users struct {
	ID               int `gorm:"primary_key"` // primary key
	Email            string
	Name             string
	UserFollowGenres []UserFollowGenres // has many UserFollowGenres
	UserFollowPrefs  []UserFollowPrefs  // has many UserFollowPrefs
	UserKeepStatus   []UserKeepStatus   // has many UserKeepStatus
	UserTerminals    []UserTerminals    // has many UserTerminals
	CreatedAt        time.Time          // timestamp
	DeletedAt        *time.Time         // nullable timestamp (soft delete)
	UpdatedAt        time.Time          // timestamp
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m Users) TableName() string {
	return "users"

}

// UsersDB is the implementation of the storage interface for
// Users.
type UsersDB struct {
	Db *gorm.DB
}

// NewUsersDB creates a new storage type.
func NewUsersDB(db *gorm.DB) *UsersDB {
	return &UsersDB{Db: db}
}

// DB returns the underlying database.
func (m *UsersDB) DB() interface{} {
	return m.Db
}

// UsersStorage represents the storage interface.
type UsersStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*Users, error)
	Get(ctx context.Context, id int) (*Users, error)
	Add(ctx context.Context, users *Users) error
	Update(ctx context.Context, users *Users) error
	Delete(ctx context.Context, id int) error
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *UsersDB) TableName() string {
	return "users"

}

// CRUD Functions

// Get returns a single Users as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *UsersDB) Get(ctx context.Context, id int) (*Users, error) {
	defer goa.MeasureSince([]string{"goa", "db", "users", "get"}, time.Now())

	var native Users
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of Users
func (m *UsersDB) List(ctx context.Context) ([]*Users, error) {
	defer goa.MeasureSince([]string{"goa", "db", "users", "list"}, time.Now())

	var objs []*Users
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *UsersDB) Add(ctx context.Context, model *Users) error {
	defer goa.MeasureSince([]string{"goa", "db", "users", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding Users", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *UsersDB) Update(ctx context.Context, model *Users) error {
	defer goa.MeasureSince([]string{"goa", "db", "users", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating Users", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *UsersDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "users", "delete"}, time.Now())

	var obj Users

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting Users", "error", err.Error())
		return err
	}

	return nil
}
